### ISSUE TITLE
Please add the ability to use HTTPS

### ISSUE THREAD

**Issue by nexusle** [buddyshome/homebridge-senec-battery#23]
My SENEC Battery isn‘t available at port 80. So this plugin need a connection over port 443 with ignoring cert issues.

**Comment by buddyshome** [comment]
Hi Nexusle,

please try out this statement and replace the ip address with the address of your battery.
I hope this works without authentication!
I am doing this in my freetime. So I would appreciate if you meet me half way by providing a working curl.

Alex

`curl -k -X POST "https://<IP_ADDRESS>/lala.cgi" -H "Content-Type: application/json" -d "{ \"ENERGY\": { \"GUI_HOUSE_POW\": \"\", \"GUI_GRID_POW\": \"\", \"GUI_INVERTER_POWER\": \"\", \"GUI_BAT_DATA_POWER\": \"\", \"GUI_BAT_DATA_FUEL_CHARGE\": \"\", \"STAT_STATE\": \"\", \"STAT_STATE_TEXT\": \"\" }, \"STATISTIC\": { \"LIVE_GRID_IMPORT\": \"\" }, \"PM1OBJ1\": { \"P_AC\": \"\" } }"
`

**Comment by nexusle** [comment]
Hey,

I get this back:

`{"ENERGY":{"GUI_HOUSE_POW":"fl_43B86753","GUI_GRID_POW":"fl_C14BAE14","GUI_INVERTER_POWER":"fl_80000000","GUI_BAT_DATA_POWER":"fl_C3BEC4C4","GUI_BAT_DATA_FUEL_CHARGE":"fl_4236FA8E","STAT_STATE":"u8_10","STAT_STATE_TEXT":"VARIABLE_NOT_FOUND"},"STATISTIC":{"LIVE_GRID_IMPORT":"VARIABLE_NOT_FOUND"},"PM1OBJ1":{"P_AC":["fl_C393CCCD","fl_4283A8F6","fl_43590A3D"]}} `

**Comment by nexusle** [comment]
This is witz port 80 (http://):

`curl: (7) Failed to connect to  xxx.xxx.xxx.xxx port 80 after 0 ms: Couldn't connect to server `

**Comment by buddyshome** [comment]
Can you please try again. I released a package .30 with SSL feature.

**Comment by nexusle** [comment]
Thanks. This works now :-)
